apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-checker
  namespace: todo-list
  labels:
    app: id-checker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: id-checker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: id-checker
    spec:
      hostAliases:
        - ip: "192.168.1.67"
          hostnames:
            - "cob.cobden.net"
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: id-checker
          image: containers.chewed-k8s.net/todo-list/id-checker:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          ports:
            - containerPort: 80
            - containerPort: 3000
          env:
            - name: KEYCLOAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: id-checker-secrets
                  key: keycloak-secret
            - name: KEYCLOAK_CLIENT
              valueFrom:
                secretKeyRef:
                  name: id-checker-secrets
                  key: keycloak-client
            - name: KEYCLOAK_REALM
              valueFrom:
                secretKeyRef:
                  key: keycloak-realm
                  name: id-checker-secrets
            - name: KEYCLOAK_HOSTNAME
              valueFrom:
                secretKeyRef:
                  key: keycloak-hostname
                  name: id-checker-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: id-checker
  namespace: todo-list
  labels:
    app: id-checker
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: id-checker
