apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-checker
  namespace: todo-list
  labels:
    app: keys-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: id-checker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: id-checker
    spec:
      hostAliases:
        - ip: "192.168.1.67"
          hostnames:
            - "cob.cobden.net"
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: id-checker
          image: containers.chewed-k8s.net/todo-list/id-checker:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /health
              port: 80
          ports:
            - containerPort: 80
          env:
            - name: KEYCLOAK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: id-checker-secrets
                  key: keycloak-token
            - name: KEYCLOAK_CLIENT
              valueFrom:
                secretKeyRef:
                  name: id-checker-secrets
                  key: keycloak-client

---
apiVersion: v1
kind: Service
metadata:
  name: id-checker
  namespace: todo-list
  labels:
    app: id-checker
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 80
  selector:
    app: id-checker

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: id-checker
  namespace: todo-list
  annotations:
    cert-manager.io/cluster-issuer: live-issuer
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: id-checker
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - id-checker.todo-list.app
      secretName: id-checker-service-tls
  rules:
    - host: id-checker.todo-list.app
      http:
        paths:
          - path: /v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: id-checker
                port:
                  number: 80
